### ISSUE TITLE
private method `include' called for String:Class (NoMethodError)

### ISSUE THREAD

**Issue by hideokamoto** [kumogata/kumogata2#2]
## Gemfile

```
# A sample Gemfile
source "https://rubygems.org"

gem 'kumogata2'
gem 'amino'
gem 'rake'

group :development do
  gem 'pry'
  gem 'pry-doc'
end
```
## Run Commands

```
$ bundle
$ kumogata2
/Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.5/lib/kumogata2/ext/string_ext.rb:35:in `<top (required)>': private method `include' called for String:Class (NoMethodError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.5/lib/kumogata2.rb:16:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.5/exe/kumogata2:3:in `<top (required)>'
    from /usr/bin/kumogata2:23:in `load'
    from /usr/bin/kumogata2:23:in `<main>'
```

**Comment by winebarrel** [comment]
Thanks for your report 😃 
This issue has been fixed.
Please try v0.1.6

**Comment by hideokamoto** [comment]
Thanks!
but another problem happend...

```
% kumogata2 convert single-hvm.rb
[ERROR] undefined method `match' for nil:NilClass
```

```
% kumogata2 list
[ERROR] undefined method `match' for nil:NilClass
```

**Comment by winebarrel** [comment]
Please write your ruby version and run kumogata2 wih `--debug` option, and puts backtrace.

**Comment by hideokamoto** [comment]
``` Gemfile
# A sample Gemfile
source "https://rubygems.org"

gem 'kumogata2'
gem 'amino'
gem 'rake'

group :development do
  gem 'pry'
  gem 'pry-doc'
end
```

```
$ kumogata2 convert single-hvm.rb --debug
[ERROR] undefined method `match' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region': undefined method `match' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:66:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:66:in `find'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:66:in `partition_matching_region'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:55:in `get_partition'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:26:in `endpoint_for'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:10:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:64:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:64:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:199:in `block in resolve_defaults'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:57:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:57:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:198:in `resolve_defaults'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:194:in `value_at'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:183:in `block in resolve'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:183:in `resolve'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:171:in `apply_defaults'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/configuration.rb:144:in `build!'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/base.rb:68:in `build_config'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/base.rb:19:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/base.rb:105:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.6/lib/kumogata2/client.rb:6:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.6/exe/kumogata2:18:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.6/exe/kumogata2:18:in `main'
    from /Library/Ruby/Gems/2.0.0/gems/kumogata2-0.1.6/exe/kumogata2:46:in `<top (required)>'
    from /usr/bin/kumogata2:23:in `load'
    from /usr/bin/kumogata2:23:in `<main>'
```

```
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

Thanks!

**Comment by winebarrel** [comment]
Thank you for your report 😃 
Please try the following:

``` sh
gem update kumogata2
gem update kumogata2-plugin-ruby
export AWS_REGION=ap-northeast-1
kumogata2 convert single-hvm.rb
```

**Comment by hideokamoto** [comment]
I'm sorry to late...
I try it again today, then it works completely!!

```
$ kumogata2 validate example.rb 
Template validated successfully

$ kumogata2 convert example.rb 
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Kumogata Sample Template\nYou can use Here document!\n",
  "Parameters": {
    "InstanceType": {
      "Default": "t2.micro",
      "Description": "Instance Type",
      "Type": "String"
    }
  },
  "Resources": {
    "myEC2Instance": {
      "Type": "AWS::EC2::Instance",
      "Properties": {
        "ImageId": "ami-XXXXXXXX",
        "InstanceType": {
          "Ref": "InstanceType"
        },
        "KeyName": "your_key_name",
        "UserData": {
          "Fn::Base64": "#!/bin/bash\nyum install -y httpd\nservice httpd start\n"
        }
      }
    }
  }
}
```


Thanks for support me :)

**Comment by n0ts** [comment]
Thanks!
